name = "LibModbus"
uuid = "eb9b09e8-e158-48db-9998-d0f1810f0d04"
authors = ["kagalenko-m-b <16374215+kagalenko-m-b@users.noreply.github.com>"]
version = "0.1.0"

[deps]
LibModbus_jll = "f28bf708-275a-52ef-9ea6-4821c17573f9"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
